version: '3'

services:
  proyecto:
    build: proyecto
    mem_limit: 512m
    ports:
      - "8090:8090"
    environment:
      DB_URL: jdbc:mysql://bd_plaza:3306/bd_plazavea?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root123
    restart: always
    depends_on:
      bd_plaza:
          condition: service_healthy
  bd_plaza:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: bd_plazavea
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10